"""Legacy-parity tables — reflected 1:1 from the legacy DB schema.

These legacy tables (AI-Portal V2) had no model in the initial AZI migration.
Each class here is generated by reflecting the live database, so the columns and
types mirror the real tables exactly and the ORM can read/write them. They carry
no routers yet — wire up APIs per feature as needed. Imported in `main.py` so the
models register on `Base.metadata` (create_all is a no-op for existing tables).
"""

from __future__ import annotations

from datetime import datetime  # noqa: F401  (used in Mapped[datetime] annotations)

from sqlalchemy import (
    JSON,
    Boolean,
    DateTime,
    Float,
    Integer,
    Numeric,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import ARRAY
from sqlalchemy.orm import Mapped, mapped_column

from core.database import Base


# NOTE: AuditLogs is modeled in core/audit.py — intentionally not redefined here.


class BatchOrderSession(Base):
    __tablename__ = "BatchOrderSession"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    title: Mapped[str | None] = mapped_column(String)
    facilityDetails: Mapped[dict | None] = mapped_column(JSON)
    locationDetails: Mapped[dict | None] = mapped_column(JSON)
    panelDetails: Mapped[dict | None] = mapped_column(JSON)
    testDetails: Mapped[dict | None] = mapped_column(JSON)
    physicianDetails: Mapped[dict | None] = mapped_column(JSON)
    numberOfOrders: Mapped[int | None] = mapped_column(Integer)
    numberOfValidOrders: Mapped[int | None] = mapped_column(Integer)
    numberOfInValidOrders: Mapped[int | None] = mapped_column(Integer)
    isGenerated: Mapped[bool | None] = mapped_column(Boolean)
    isValid: Mapped[bool | None] = mapped_column(Boolean)
    dataColumns: Mapped[list | None] = mapped_column(ARRAY(String))
    createdByDetails: Mapped[dict | None] = mapped_column(JSON)
    attachmentDetails: Mapped[dict | None] = mapped_column(JSON)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class BatchOrderSessionPatient(Base):
    __tablename__ = "BatchOrderSessionPatient"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    title: Mapped[str | None] = mapped_column(String)
    facilityDetails: Mapped[dict | None] = mapped_column(JSON)
    locationDetails: Mapped[dict | None] = mapped_column(JSON)
    numberOfPatients: Mapped[int | None] = mapped_column(Integer)
    numberOfValidPatients: Mapped[int | None] = mapped_column(Integer)
    numberOfInValidPatients: Mapped[int | None] = mapped_column(Integer)
    isGenerated: Mapped[bool | None] = mapped_column(Boolean)
    isValid: Mapped[bool | None] = mapped_column(Boolean)
    dataColumns: Mapped[list | None] = mapped_column(ARRAY(String))
    createdByDetails: Mapped[dict | None] = mapped_column(JSON)
    attachmentDetails: Mapped[dict | None] = mapped_column(JSON)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class BatchOrderSessionValue(Base):
    __tablename__ = "BatchOrderSessionValue"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    batchOrderSessionId: Mapped[int | None] = mapped_column(Integer)
    facilityDetails: Mapped[dict | None] = mapped_column(JSON)
    locationDetails: Mapped[dict | None] = mapped_column(JSON)
    physicianDetails: Mapped[dict | None] = mapped_column(JSON)
    patientDetails: Mapped[dict | None] = mapped_column(JSON)
    panelDetails: Mapped[dict | None] = mapped_column(JSON)
    testDetails: Mapped[dict | None] = mapped_column(JSON)
    createdByDetails: Mapped[dict | None] = mapped_column(JSON)
    barcode: Mapped[str | None] = mapped_column(String)
    dateOfCollection: Mapped[str | None] = mapped_column(String)
    timeOfCollection: Mapped[str | None] = mapped_column(String)
    externalReferenceNumber: Mapped[str | None] = mapped_column(String)
    dateTimeOfCollection: Mapped[dict | None] = mapped_column(JSON)
    sendResultToPatient: Mapped[bool | None] = mapped_column(Boolean)
    modeOfPayment: Mapped[str | None] = mapped_column(String)
    status: Mapped[str | None] = mapped_column(String)
    isGenerated: Mapped[bool | None] = mapped_column(Boolean)
    isPriorityOrder: Mapped[bool | None] = mapped_column(Boolean)
    isValid: Mapped[bool | None] = mapped_column(Boolean)
    isConsentSigned: Mapped[bool | None] = mapped_column(Boolean)
    labDetails: Mapped[dict | None] = mapped_column(JSON)
    reasonForVisit: Mapped[str | None] = mapped_column(String)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class BiomarkerAttachments(Base):
    __tablename__ = "BiomarkerAttachments"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    biomarkerId: Mapped[int | None] = mapped_column(Integer)
    fileName: Mapped[str | None] = mapped_column(String)
    mimeType: Mapped[str | None] = mapped_column(String)
    fileSize: Mapped[int | None] = mapped_column(Integer)
    path: Mapped[str | None] = mapped_column(String)
    secureUrl: Mapped[str | None] = mapped_column(String)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class BiomarkerReportConfiguration(Base):
    __tablename__ = "BiomarkerReportConfiguration"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    biomarkerId: Mapped[int | None] = mapped_column(Integer)
    gender: Mapped[str | None] = mapped_column(String)
    age: Mapped[str | None] = mapped_column(String)
    rules: Mapped[list | None] = mapped_column(ARRAY(JSON))
    expectedResults: Mapped[str | None] = mapped_column(String)
    biomarkerNotes: Mapped[str | None] = mapped_column(Text)
    isBiomarkerNoteAvailable: Mapped[bool | None] = mapped_column(Boolean)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class BiomarkerStaticData(Base):
    __tablename__ = "BiomarkerStaticData"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    title: Mapped[str | None] = mapped_column(String)
    value: Mapped[list | None] = mapped_column(ARRAY(JSON))
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class BiomarkerStaticSampleTypes(Base):
    __tablename__ = "BiomarkerStaticSampleTypes"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    sampleType: Mapped[str | None] = mapped_column(String)
    sampleCollectionDeviceName: Mapped[list | None] = mapped_column(ARRAY(JSON))
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class CustomerToken(Base):
    __tablename__ = "CustomerToken"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    customerId: Mapped[int | None] = mapped_column(Integer)
    token: Mapped[str | None] = mapped_column(Text)
    expiryDate: Mapped[str | None] = mapped_column(String)
    isActive: Mapped[bool | None] = mapped_column(Boolean)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class D2C_CustomerOrderItems(Base):
    __tablename__ = "D2C_CustomerOrderItems"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    orderId: Mapped[float | None] = mapped_column(Numeric)
    orderCode: Mapped[str | None] = mapped_column(String)
    customerId: Mapped[float | None] = mapped_column(Numeric)
    patientId: Mapped[float | None] = mapped_column(Numeric)
    productId: Mapped[float | None] = mapped_column(Numeric)
    quantity: Mapped[float | None] = mapped_column(Numeric)
    price: Mapped[float | None] = mapped_column(Numeric)
    totalPrice: Mapped[float | None] = mapped_column(Numeric)
    testId: Mapped[float | None] = mapped_column(Numeric)
    dateOfOrder: Mapped[datetime | None] = mapped_column(DateTime)
    status: Mapped[str | None] = mapped_column(String)
    reasonForCancellation: Mapped[str | None] = mapped_column(String)
    paymentStatus: Mapped[str | None] = mapped_column(String)
    paymentDate: Mapped[datetime | None] = mapped_column(DateTime)
    paymentMode: Mapped[str | None] = mapped_column(String)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class EnbCheckLogs(Base):
    __tablename__ = "EnbCheckLogs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    controlNumber: Mapped[int | None] = mapped_column(Integer)
    patientId: Mapped[int | None] = mapped_column(Integer)
    patientInsuranceId: Mapped[int | None] = mapped_column(Integer)
    orderId: Mapped[int | None] = mapped_column(Integer)
    orderInsuranceId: Mapped[int | None] = mapped_column(Integer)
    enbServiceProviderName: Mapped[str | None] = mapped_column(String)
    requestRawJsonBody: Mapped[dict | None] = mapped_column(JSON)
    requestDataFileURL: Mapped[str | None] = mapped_column(String)
    responseRawJsonBody: Mapped[dict | None] = mapped_column(JSON)
    responseDataFileURL: Mapped[str | None] = mapped_column(String)
    createdBy: Mapped[int | None] = mapped_column(Integer)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class EnbLog(Base):
    __tablename__ = "EnbLog"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    patientId: Mapped[int | None] = mapped_column(Integer)
    patientInsuranceId: Mapped[int | None] = mapped_column(Integer)
    finalJson: Mapped[dict | None] = mapped_column(JSON)
    formattedJson: Mapped[dict | None] = mapped_column(JSON)
    error: Mapped[dict | None] = mapped_column(JSON)
    createdBy: Mapped[int | None] = mapped_column(Integer)
    controlNumber: Mapped[str | None] = mapped_column(String)
    payload: Mapped[dict | None] = mapped_column(JSON)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class FacilityStaticData(Base):
    __tablename__ = "FacilityStaticData"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    title: Mapped[str | None] = mapped_column(String)
    value: Mapped[list | None] = mapped_column(ARRAY(JSON))
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class LabImage(Base):
    __tablename__ = "LabImage"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    labId: Mapped[int | None] = mapped_column(Integer)
    attachmentName: Mapped[str | None] = mapped_column(String)
    secureUrl: Mapped[str | None] = mapped_column(String)
    mimeType: Mapped[str | None] = mapped_column(String)
    size: Mapped[int | None] = mapped_column(Integer)
    title: Mapped[str | None] = mapped_column(String)
    attachmentType: Mapped[str | None] = mapped_column(String)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class LabOsBatchList(Base):
    __tablename__ = "LabOsBatchList"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    batchName: Mapped[str | None] = mapped_column(String)
    worklistId: Mapped[int | None] = mapped_column(Integer)
    selectedSamples: Mapped[list | None] = mapped_column(ARRAY(Integer))
    analyserIds: Mapped[list | None] = mapped_column(ARRAY(Integer))
    testId: Mapped[int | None] = mapped_column(Integer)
    biomarkerId: Mapped[int | None] = mapped_column(Integer)
    reagentIds: Mapped[list | None] = mapped_column(ARRAY(Integer))
    reagentLots: Mapped[list | None] = mapped_column(ARRAY(Integer))
    labId: Mapped[int | None] = mapped_column(Integer)
    processingTechIds: Mapped[list | None] = mapped_column(ARRAY(Integer))
    approvingTechIds: Mapped[list | None] = mapped_column(ARRAY(Integer))
    createdBy: Mapped[int | None] = mapped_column(Integer)
    updatedBy: Mapped[int | None] = mapped_column(Integer)
    updatedOn: Mapped[datetime | None] = mapped_column(DateTime)
    createdOn: Mapped[datetime | None] = mapped_column(DateTime)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class LabOsCapa(Base):
    __tablename__ = "LabOsCapa"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    issue: Mapped[str | None] = mapped_column(String)
    impact: Mapped[str | None] = mapped_column(String)
    root_cause: Mapped[str | None] = mapped_column(String)
    immediate_action: Mapped[str | None] = mapped_column(String)
    preventative_action: Mapped[str | None] = mapped_column(String)
    monitered: Mapped[str | None] = mapped_column(String)
    attachment_urls: Mapped[dict | None] = mapped_column(JSON)
    supervisor: Mapped[bool | None] = mapped_column(Boolean)
    comments: Mapped[str | None] = mapped_column(Text)
    created_by: Mapped[int | None] = mapped_column(Integer)
    lab_id: Mapped[int | None] = mapped_column(Integer)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class LabOsCategory(Base):
    __tablename__ = "LabOsCategory"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    LabTypeCategory: Mapped[str | None] = mapped_column(String)
    SubModules: Mapped[list | None] = mapped_column(ARRAY(String))
    Analysers: Mapped[list | None] = mapped_column(ARRAY(String))
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class LabOsControlMapping(Base):
    __tablename__ = "LabOsControlMapping"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    runFileTargetName: Mapped[str | None] = mapped_column(String)
    biomarkerId: Mapped[int | None] = mapped_column(Integer)
    testId: Mapped[int | None] = mapped_column(Integer)
    cutOffMin: Mapped[int | None] = mapped_column(Integer)
    cutOffMax: Mapped[int | None] = mapped_column(Integer)
    control: Mapped[str | None] = mapped_column(String)
    result: Mapped[str | None] = mapped_column(String)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class LabOsFiles(Base):
    __tablename__ = "LabOsFiles"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    department: Mapped[str | None] = mapped_column(String)
    attachments: Mapped[dict | None] = mapped_column(JSON)
    title: Mapped[str | None] = mapped_column(String)
    folderId: Mapped[int | None] = mapped_column(Integer)
    createdBy: Mapped[int | None] = mapped_column(Integer)
    updatedBy: Mapped[int | None] = mapped_column(Integer)
    isMarkForReview: Mapped[bool | None] = mapped_column(Boolean)
    isReviewed: Mapped[bool | None] = mapped_column(Boolean)
    reviewedBy: Mapped[int | None] = mapped_column(Integer)
    reviewedOn: Mapped[datetime | None] = mapped_column(DateTime)
    labId: Mapped[int | None] = mapped_column(Integer)
    serialCount: Mapped[int | None] = mapped_column(Integer)
    isDeleted: Mapped[bool | None] = mapped_column(Boolean)
    deletedBy: Mapped[int | None] = mapped_column(Integer)
    deletedOn: Mapped[datetime | None] = mapped_column(DateTime)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class LabOsFolders(Base):
    __tablename__ = "LabOsFolders"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    department: Mapped[str | None] = mapped_column(String)
    name: Mapped[str | None] = mapped_column(String)
    parent: Mapped[int | None] = mapped_column(Integer)
    labId: Mapped[int | None] = mapped_column(Integer)
    serialCount: Mapped[int | None] = mapped_column(Integer)
    createdBy: Mapped[int | None] = mapped_column(Integer)
    isDeleted: Mapped[bool | None] = mapped_column(Boolean)
    deletedBy: Mapped[int | None] = mapped_column(Integer)
    deletedOn: Mapped[datetime | None] = mapped_column(DateTime)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class LabOsInventory(Base):
    __tablename__ = "LabOsInventory"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    inventory_category: Mapped[str | None] = mapped_column(String)
    item_name: Mapped[str | None] = mapped_column(String)
    item_type: Mapped[str | None] = mapped_column(String)
    manufacturer: Mapped[str | None] = mapped_column(String)
    catalog_number: Mapped[str | None] = mapped_column(String)
    batch_number: Mapped[str | None] = mapped_column(String)
    lot_number: Mapped[str | None] = mapped_column(String)
    expiry_date: Mapped[datetime | None] = mapped_column(DateTime)
    stock_quantity: Mapped[str | None] = mapped_column(String)
    stock_units: Mapped[str | None] = mapped_column(String)
    alert_quantity: Mapped[str | None] = mapped_column(String)
    storage_location: Mapped[str | None] = mapped_column(String)
    qc_status: Mapped[str | None] = mapped_column(String)
    event: Mapped[str | None] = mapped_column(String)
    status: Mapped[str | None] = mapped_column(String)
    department: Mapped[str | None] = mapped_column(String)
    created_by: Mapped[int | None] = mapped_column(Integer)
    lab_id: Mapped[int | None] = mapped_column(Integer)
    created_on: Mapped[datetime | None] = mapped_column(DateTime)
    updated_on: Mapped[datetime | None] = mapped_column(DateTime)
    childProduct: Mapped[bool | None] = mapped_column(Boolean)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class LabOsResultLogs(Base):
    __tablename__ = "LabOsResultLogs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    testId: Mapped[int | None] = mapped_column(Integer)
    title: Mapped[str | None] = mapped_column(String)
    sampleJson: Mapped[dict | None] = mapped_column(JSON)
    status: Mapped[str | None] = mapped_column(String)
    plateNo: Mapped[str | None] = mapped_column(String)
    createdBy: Mapped[int | None] = mapped_column(Integer)
    isCompleted: Mapped[bool | None] = mapped_column(Boolean)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class LabOsWorkList(Base):
    __tablename__ = "LabOsWorkList"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    worklistId: Mapped[str | None] = mapped_column(String)
    createdBy: Mapped[int | None] = mapped_column(Integer)
    updatedBy: Mapped[int | None] = mapped_column(Integer)
    createdOn: Mapped[datetime | None] = mapped_column(DateTime)
    updatedOn: Mapped[datetime | None] = mapped_column(DateTime)
    assignedSamples: Mapped[dict | None] = mapped_column(JSON)
    rerunSamples: Mapped[list | None] = mapped_column(ARRAY(String))
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class LabStaticData(Base):
    __tablename__ = "LabStaticData"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    title: Mapped[str | None] = mapped_column(String)
    value: Mapped[list | None] = mapped_column(ARRAY(JSON))
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class LinkLabBiomarker(Base):
    __tablename__ = "LinkLabBiomarker"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    labId: Mapped[int | None] = mapped_column(Integer)
    biomarkerId: Mapped[int | None] = mapped_column(Integer)
    isActive: Mapped[bool | None] = mapped_column(Boolean)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class LinkLabPanel(Base):
    __tablename__ = "LinkLabPanel"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    labId: Mapped[int | None] = mapped_column(Integer)
    panelId: Mapped[int | None] = mapped_column(Integer)
    isActive: Mapped[bool | None] = mapped_column(Boolean)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class LinkLabTest(Base):
    __tablename__ = "LinkLabTest"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    labId: Mapped[int | None] = mapped_column(Integer)
    testId: Mapped[int | None] = mapped_column(Integer)
    isActive: Mapped[bool | None] = mapped_column(Boolean)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class LinkLocationBiomarker(Base):
    __tablename__ = "LinkLocationBiomarker"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    locationId: Mapped[int | None] = mapped_column(Integer)
    biomarkerId: Mapped[int | None] = mapped_column(Integer)
    isActive: Mapped[bool | None] = mapped_column(Boolean)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class LinkLocationPanel(Base):
    __tablename__ = "LinkLocationPanel"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    locationId: Mapped[int | None] = mapped_column(Integer)
    panelId: Mapped[int | None] = mapped_column(Integer)
    isActive: Mapped[bool | None] = mapped_column(Boolean)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class LinkLocationTest(Base):
    __tablename__ = "LinkLocationTest"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    locationId: Mapped[int | None] = mapped_column(Integer)
    testId: Mapped[int | None] = mapped_column(Integer)
    isActive: Mapped[bool | None] = mapped_column(Boolean)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class LinkPatientLocation(Base):
    __tablename__ = "LinkPatientLocation"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    locationId: Mapped[int | None] = mapped_column(Integer)
    patientId: Mapped[int | None] = mapped_column(Integer)
    facilityId: Mapped[int | None] = mapped_column(Integer)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class LocationFavoriteIcdCode(Base):
    __tablename__ = "LocationFavoriteIcdCode"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    locationId: Mapped[int | None] = mapped_column(Integer)
    icdCodeId: Mapped[int | None] = mapped_column(Integer)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class Medication(Base):
    __tablename__ = "Medication"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    brandName: Mapped[str | None] = mapped_column(Text)
    genericName: Mapped[str | None] = mapped_column(Text)
    dosageForm: Mapped[str | None] = mapped_column(Text)
    dosage: Mapped[str | None] = mapped_column(Text)
    unit: Mapped[str | None] = mapped_column(Text)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class OCREOBBatch(Base):
    __tablename__ = "OCREOBBatch"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    name: Mapped[str | None] = mapped_column(String)
    status: Mapped[str | None] = mapped_column(String)
    numberOfFiles: Mapped[int | None] = mapped_column(Integer)
    createdBy: Mapped[int | None] = mapped_column(Integer)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class OCREOBBatchSession(Base):
    __tablename__ = "OCREOBBatchSession"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    batchId: Mapped[int | None] = mapped_column(Integer)
    filePath: Mapped[str | None] = mapped_column(String)
    name: Mapped[str | None] = mapped_column(String)
    description: Mapped[str | None] = mapped_column(String)
    status: Mapped[str | None] = mapped_column(String)
    numberOfFiles: Mapped[int | None] = mapped_column(Integer)
    createdBy: Mapped[int | None] = mapped_column(Integer)
    filename: Mapped[str | None] = mapped_column(String)
    isProcessed: Mapped[bool | None] = mapped_column(Boolean)
    mimetype: Mapped[str | None] = mapped_column(String)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class OCREOBBatchSessionImages(Base):
    __tablename__ = "OCREOBBatchSessionImages"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    batchId: Mapped[int | None] = mapped_column(Integer)
    sessionId: Mapped[int | None] = mapped_column(Integer)
    filePath: Mapped[str | None] = mapped_column(String)
    filename: Mapped[str | None] = mapped_column(String)
    companyName: Mapped[str | None] = mapped_column(String)
    isSpam: Mapped[bool | None] = mapped_column(Boolean)
    isProcessed: Mapped[bool | None] = mapped_column(Boolean)
    status: Mapped[str | None] = mapped_column(String)
    createdBy: Mapped[int | None] = mapped_column(Integer)
    mimetype: Mapped[str | None] = mapped_column(String)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class OCREOBBatchSessionResults(Base):
    __tablename__ = "OCREOBBatchSessionResults"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    batchId: Mapped[int | None] = mapped_column(Integer)
    filePath: Mapped[str | None] = mapped_column(String)
    filename: Mapped[str | None] = mapped_column(String)
    mimetype: Mapped[str | None] = mapped_column(String)
    sessionId: Mapped[int | None] = mapped_column(Integer)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class OCRInferenceSession(Base):
    __tablename__ = "OCRInferenceSession"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    numberOfInferenceFiles: Mapped[int | None] = mapped_column(Integer)
    numberOfFiles: Mapped[int | None] = mapped_column(Integer)
    uploadedBy: Mapped[int | None] = mapped_column(Integer)
    status: Mapped[str | None] = mapped_column(String)
    name: Mapped[str | None] = mapped_column(String)
    comments: Mapped[str | None] = mapped_column(String)
    modeOfUpload: Mapped[str | None] = mapped_column(String)
    metaDataOfSource: Mapped[dict | None] = mapped_column(JSON)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class OCRInferenceSessionImage(Base):
    __tablename__ = "OCRInferenceSessionImage"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    fileName: Mapped[str | None] = mapped_column(String)
    secureUrl: Mapped[str | None] = mapped_column(String)
    mimetype: Mapped[str | None] = mapped_column(String)
    uploadedBy: Mapped[int | None] = mapped_column(Integer)
    inferenceSessionId: Mapped[int | None] = mapped_column(Integer)
    results: Mapped[dict | None] = mapped_column(JSON)
    companyName: Mapped[str | None] = mapped_column(String)
    ocrResponse: Mapped[dict | None] = mapped_column(JSON)
    config: Mapped[dict | None] = mapped_column(JSON)
    status: Mapped[str | None] = mapped_column(String)
    isInferenceCompleted: Mapped[bool | None] = mapped_column(Boolean)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class OCRUser(Base):
    __tablename__ = "OCRUser"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    name: Mapped[str | None] = mapped_column(String)
    secreteKey: Mapped[str | None] = mapped_column(String)
    token: Mapped[str | None] = mapped_column(Text)
    expiry: Mapped[dict | None] = mapped_column(JSON)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class OrderAttachment(Base):
    __tablename__ = "OrderAttachment"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    orderId: Mapped[int | None] = mapped_column(Integer)
    sampleId: Mapped[int | None] = mapped_column(Integer)
    attachmentType: Mapped[str | None] = mapped_column(String)
    title: Mapped[str | None] = mapped_column(String)
    secureUrl: Mapped[str | None] = mapped_column(String)
    mimeType: Mapped[str | None] = mapped_column(String)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class OrderExternalIds(Base):
    __tablename__ = "OrderExternalIds"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    orderId: Mapped[int | None] = mapped_column(Integer)
    serviceName: Mapped[str | None] = mapped_column(String)
    externalId: Mapped[str | None] = mapped_column(String)
    isActive: Mapped[bool | None] = mapped_column(Boolean)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class OrderFlag(Base):
    __tablename__ = "OrderFlag"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    orderId: Mapped[int | None] = mapped_column(Integer)
    resultReportedToInterface: Mapped[bool | None] = mapped_column(Boolean)
    isArkstoneReportRequired: Mapped[bool | None] = mapped_column(Boolean)
    isArkstoneReportGenerated: Mapped[bool | None] = mapped_column(Boolean)
    isEmgenexReportRequired: Mapped[bool | None] = mapped_column(Boolean)
    isEmgenexReportGenerated: Mapped[bool | None] = mapped_column(Boolean)
    isChoicePharmDReportRequired: Mapped[bool | None] = mapped_column(Boolean)
    isChoicePharmDReportGenerated: Mapped[bool | None] = mapped_column(Boolean)
    isDrChronoSyncRequired: Mapped[bool | None] = mapped_column(Boolean)
    isDrChronoOrderCreated: Mapped[bool | None] = mapped_column(Boolean)
    isDrChronoOrderResultSubmitted: Mapped[bool | None] = mapped_column(Boolean)
    createdBy: Mapped[int | None] = mapped_column(Integer)
    updatedBy: Mapped[int | None] = mapped_column(Integer)
    createdAt: Mapped[dict | None] = mapped_column(JSON)
    updatedAt: Mapped[dict | None] = mapped_column(JSON)

class OrderFlagV2(Base):
    __tablename__ = "OrderFlagV2"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    resultReportedToInterface: Mapped[bool | None] = mapped_column(Boolean)
    orderId: Mapped[int | None] = mapped_column(Integer)
    reportingService: Mapped[str | None] = mapped_column(String)
    isReportGenerated: Mapped[bool | None] = mapped_column(Boolean)
    createdBy: Mapped[int | None] = mapped_column(Integer)
    updatedBy: Mapped[int | None] = mapped_column(Integer)
    createdAt: Mapped[dict | None] = mapped_column(JSON)
    updatedAt: Mapped[dict | None] = mapped_column(JSON)

class OrderSampleGrouping(Base):
    __tablename__ = "OrderSampleGrouping"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    orderId: Mapped[int | None] = mapped_column(Integer)
    orderType: Mapped[str | None] = mapped_column(String)
    panelId: Mapped[int | None] = mapped_column(Integer)
    testId: Mapped[int | None] = mapped_column(Integer)
    biomarkerId: Mapped[int | None] = mapped_column(Integer)
    pdfDetails: Mapped[dict | None] = mapped_column(JSON)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class OrderStaticData(Base):
    __tablename__ = "OrderStaticData"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    title: Mapped[str | None] = mapped_column(String)
    value: Mapped[list | None] = mapped_column(ARRAY(JSON))
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class PanelIcdCode(Base):
    __tablename__ = "PanelIcdCode"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    panelId: Mapped[int | None] = mapped_column(Integer)
    icdCode: Mapped[str | None] = mapped_column(String)
    description: Mapped[str | None] = mapped_column(String)
    linkedToLocationId: Mapped[int | None] = mapped_column(Integer)
    createdBy: Mapped[int | None] = mapped_column(Integer)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class PanelImage(Base):
    __tablename__ = "PanelImage"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    panelId: Mapped[int | None] = mapped_column(Integer)
    attachmentName: Mapped[str | None] = mapped_column(String)
    secureUrl: Mapped[str | None] = mapped_column(String)
    mimeType: Mapped[str | None] = mapped_column(String)
    size: Mapped[int | None] = mapped_column(Integer)
    title: Mapped[str | None] = mapped_column(String)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class PanelStaticData(Base):
    __tablename__ = "PanelStaticData"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    title: Mapped[str | None] = mapped_column(String)
    value: Mapped[list | None] = mapped_column(ARRAY(JSON))
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class PanelVariableTemplate(Base):
    __tablename__ = "PanelVariableTemplate"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    panelId: Mapped[int | None] = mapped_column(Integer)
    templateName: Mapped[str | None] = mapped_column(String)
    mimeType: Mapped[str | None] = mapped_column(String)
    securePath: Mapped[str | None] = mapped_column(String)
    isActive: Mapped[bool | None] = mapped_column(Boolean)
    isDelete: Mapped[bool | None] = mapped_column(Boolean)
    createdBy: Mapped[int | None] = mapped_column(Integer)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class PatientAttachments(Base):
    __tablename__ = "PatientAttachments"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    patientId: Mapped[int | None] = mapped_column(Integer)
    title: Mapped[str | None] = mapped_column(String)
    secureUrl: Mapped[str | None] = mapped_column(String)
    mimeType: Mapped[str | None] = mapped_column(String)
    attachmentType: Mapped[str | None] = mapped_column(String)
    attachmentName: Mapped[str | None] = mapped_column(String)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class PatientExternalIds(Base):
    __tablename__ = "PatientExternalIds"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    patientId: Mapped[int | None] = mapped_column(Integer)
    serviceName: Mapped[str | None] = mapped_column(String)
    externalId: Mapped[str | None] = mapped_column(String)
    isActive: Mapped[bool | None] = mapped_column(Boolean)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class PatientIntakeResponse(Base):
    __tablename__ = "PatientIntakeResponse"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    patientId: Mapped[int | None] = mapped_column(Integer)
    responseWithCode: Mapped[dict | None] = mapped_column(JSON)
    source: Mapped[str | None] = mapped_column(String)
    startTime: Mapped[dict | None] = mapped_column(JSON)
    orderId: Mapped[int | None] = mapped_column(Integer)
    sampleId: Mapped[int | None] = mapped_column(Integer)
    formId: Mapped[int | None] = mapped_column(Integer)
    sessionId: Mapped[str | None] = mapped_column(String)
    isCompleted: Mapped[bool | None] = mapped_column(Boolean)
    shouldNotify: Mapped[bool | None] = mapped_column(Boolean)
    mlResponse: Mapped[dict | None] = mapped_column(JSON)
    mlPayload: Mapped[dict | None] = mapped_column(JSON)
    responseWithQuestion: Mapped[dict | None] = mapped_column(JSON)
    endTime: Mapped[dict | None] = mapped_column(JSON)
    testId: Mapped[int | None] = mapped_column(Integer)
    mlResponseTime: Mapped[str | None] = mapped_column(String)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class PatientStaticData(Base):
    __tablename__ = "PatientStaticData"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    title: Mapped[str | None] = mapped_column(String)
    value: Mapped[list | None] = mapped_column(ARRAY(JSON))
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class PatientToken(Base):
    __tablename__ = "PatientToken"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    patientId: Mapped[int | None] = mapped_column(Integer)
    token: Mapped[str | None] = mapped_column(Text)
    expiryDate: Mapped[str | None] = mapped_column(String)
    isActive: Mapped[bool | None] = mapped_column(Boolean)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class Plates(Base):
    __tablename__ = "Plates"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    department: Mapped[int | None] = mapped_column(Integer)
    equipment: Mapped[int | None] = mapped_column(Integer)
    plate_name: Mapped[str | None] = mapped_column(String)
    rows: Mapped[str | None] = mapped_column(String)
    row_indication_type: Mapped[str | None] = mapped_column(String)
    columns: Mapped[str | None] = mapped_column(String)
    column_indication_type: Mapped[str | None] = mapped_column(String)
    is_controls_available: Mapped[bool | None] = mapped_column(Boolean)
    controls: Mapped[dict | None] = mapped_column(JSON)
    created_by: Mapped[int | None] = mapped_column(Integer)
    updated_on: Mapped[datetime | None] = mapped_column(DateTime)
    lab_id: Mapped[int | None] = mapped_column(Integer)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class ProductCart(Base):
    __tablename__ = "ProductCart"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class ProductQuantity(Base):
    __tablename__ = "ProductQuantity"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class ProductQuantityLog(Base):
    __tablename__ = "ProductQuantityLog"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    productId: Mapped[int | None] = mapped_column(Integer)
    value: Mapped[int | None] = mapped_column(Integer)
    updatedValue: Mapped[int | None] = mapped_column(Integer)
    addedBy: Mapped[int | None] = mapped_column(Integer)
    operation: Mapped[str | None] = mapped_column(String)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class Question(Base):
    __tablename__ = "Question"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    title: Mapped[str | None] = mapped_column(String)
    code: Mapped[str | None] = mapped_column(String)
    subTitle: Mapped[str | None] = mapped_column(String)
    showLabel: Mapped[bool | None] = mapped_column(Boolean)
    formControlType: Mapped[str | None] = mapped_column(String)
    formControlSize: Mapped[str | None] = mapped_column(String)
    placeHolder: Mapped[str | None] = mapped_column(String)
    mlref: Mapped[str | None] = mapped_column(String)
    options: Mapped[list | None] = mapped_column(ARRAY(JSON))
    isSubQuestion: Mapped[bool | None] = mapped_column(Boolean)
    isMultiSelection: Mapped[bool | None] = mapped_column(Boolean)
    isHorizontalAlign: Mapped[bool | None] = mapped_column(Boolean)
    isHavingNoneOption: Mapped[bool | None] = mapped_column(Boolean)
    isRequired: Mapped[bool | None] = mapped_column(Boolean)
    isConditional: Mapped[bool | None] = mapped_column(Boolean)
    conditionRules: Mapped[list | None] = mapped_column(ARRAY(JSON))
    isActive: Mapped[bool | None] = mapped_column(Boolean)
    autoHeight: Mapped[bool | None] = mapped_column(Boolean)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class QuestionForm(Base):
    __tablename__ = "QuestionForm"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    title: Mapped[str | None] = mapped_column(String)
    descriptions: Mapped[str | None] = mapped_column(String)
    steps: Mapped[list | None] = mapped_column(ARRAY(JSON))
    isActive: Mapped[bool | None] = mapped_column(Boolean)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class QuestionFormStep(Base):
    __tablename__ = "QuestionFormStep"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    title: Mapped[str | None] = mapped_column(String)
    descriptions: Mapped[str | None] = mapped_column(String)
    assetUrl: Mapped[str | None] = mapped_column(String)
    toolTip: Mapped[str | None] = mapped_column(Text)
    canNavigateBack: Mapped[bool | None] = mapped_column(Boolean)
    proceedButtonText: Mapped[str | None] = mapped_column(String)
    canSkipTheStep: Mapped[bool | None] = mapped_column(Boolean)
    isActive: Mapped[bool | None] = mapped_column(Boolean)
    questions: Mapped[list | None] = mapped_column(ARRAY(Integer))
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class ReportArchive(Base):
    __tablename__ = "ReportArchive"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    sampleId: Mapped[int | None] = mapped_column(Integer)
    updateReason: Mapped[str | None] = mapped_column(String)
    updateType: Mapped[str | None] = mapped_column(String)
    accessionId: Mapped[str | None] = mapped_column(String)
    pdfDetails: Mapped[dict | None] = mapped_column(JSON)
    updatedFields: Mapped[dict | None] = mapped_column(JSON)
    resultVersion: Mapped[int | None] = mapped_column(Integer)
    reportVersion: Mapped[int | None] = mapped_column(Integer)
    updatedBy: Mapped[int | None] = mapped_column(Integer)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class ResultControlComment(Base):
    __tablename__ = "ResultControlComment"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    uploadResultSessionId: Mapped[int | None] = mapped_column(Integer)
    testPanelCode: Mapped[str | None] = mapped_column(String)
    resultControlId: Mapped[int | None] = mapped_column(Integer)
    createdBy: Mapped[int | None] = mapped_column(Integer)
    isCls: Mapped[bool | None] = mapped_column(Boolean)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class ResultSampleComment(Base):
    __tablename__ = "ResultSampleComment"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    resultSampleId: Mapped[int | None] = mapped_column(Integer)
    createdBy: Mapped[int | None] = mapped_column(Integer)
    isCls: Mapped[bool | None] = mapped_column(Boolean)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class ResultSampleDetail(Base):
    __tablename__ = "ResultSampleDetail"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    resultSampleId: Mapped[int | None] = mapped_column(Integer)
    wellPosition: Mapped[str | None] = mapped_column(String)
    accessionId: Mapped[str | None] = mapped_column(String)
    targetName: Mapped[str | None] = mapped_column(String)
    biomarkerId: Mapped[int | None] = mapped_column(Integer)
    biomarkerName: Mapped[str | None] = mapped_column(String)
    fluorophore: Mapped[str | None] = mapped_column(String)
    ctValue: Mapped[float | None] = mapped_column(Float)
    cutoffValue: Mapped[float | None] = mapped_column(Float)
    cutoffCycle: Mapped[float | None] = mapped_column(Float)
    result: Mapped[str | None] = mapped_column(String)
    isQuantitative: Mapped[bool | None] = mapped_column(Boolean)
    gender: Mapped[str | None] = mapped_column(String)
    age: Mapped[int | None] = mapped_column(Integer)
    value1: Mapped[str | None] = mapped_column(String)
    expression: Mapped[str | None] = mapped_column(String)
    value2: Mapped[str | None] = mapped_column(String)
    units: Mapped[str | None] = mapped_column(String)
    notes: Mapped[str | None] = mapped_column(Text)
    color: Mapped[str | None] = mapped_column(String)
    reasonForChange: Mapped[str | None] = mapped_column(Text)
    isOutOfRange: Mapped[bool | None] = mapped_column(Boolean)
    version: Mapped[int | None] = mapped_column(Integer)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class ResultSampleMetaDetails(Base):
    __tablename__ = "ResultSampleMetaDetails"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    resultSampleId: Mapped[int | None] = mapped_column(Integer)
    accessionId: Mapped[str | None] = mapped_column(String)
    version: Mapped[int | None] = mapped_column(Integer)
    sampleId: Mapped[int | None] = mapped_column(Integer)
    orderId: Mapped[int | None] = mapped_column(Integer)
    patientFirstName: Mapped[str | None] = mapped_column(String)
    patientMiddleName: Mapped[str | None] = mapped_column(String)
    patientLastName: Mapped[str | None] = mapped_column(String)
    patientPrefix: Mapped[str | None] = mapped_column(String)
    patientSuffix: Mapped[str | None] = mapped_column(String)
    patientGender: Mapped[str | None] = mapped_column(String)
    patientDOB: Mapped[str | None] = mapped_column(String)
    patientEmail: Mapped[str | None] = mapped_column(String)
    reasonForAmendment: Mapped[str | None] = mapped_column(String)
    reasonForCorrection: Mapped[str | None] = mapped_column(String)
    addedBy: Mapped[int | None] = mapped_column(Integer)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class ResultSession(Base):
    __tablename__ = "ResultSession"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    testId: Mapped[int | None] = mapped_column(Integer)
    testDetails: Mapped[dict | None] = mapped_column(JSON)
    createdBy: Mapped[str | None] = mapped_column(String)
    createdByDetails: Mapped[dict | None] = mapped_column(JSON)
    numberOfSamples: Mapped[int | None] = mapped_column(Integer)
    numberOfSamplesMatched: Mapped[int | None] = mapped_column(Integer)
    numberOfSamplesUnMatched: Mapped[int | None] = mapped_column(Integer)
    isGenerateRequestSubmitted: Mapped[bool | None] = mapped_column(Boolean)
    attachmentDetails: Mapped[dict | None] = mapped_column(JSON)
    timezone: Mapped[str | None] = mapped_column(String)
    biomarkerId: Mapped[int | None] = mapped_column(Integer)
    biomarkerDetails: Mapped[dict | None] = mapped_column(JSON)
    reportId: Mapped[int | None] = mapped_column(Integer)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class ResultSessionValue(Base):
    __tablename__ = "ResultSessionValue"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    sessionId: Mapped[int | None] = mapped_column(Integer)
    results: Mapped[dict | None] = mapped_column(JSON)
    sampleDetails: Mapped[dict | None] = mapped_column(JSON)
    orderDetails: Mapped[dict | None] = mapped_column(JSON)
    pdfDetails: Mapped[dict | None] = mapped_column(JSON)
    isPdfGenerated: Mapped[bool | None] = mapped_column(Boolean)
    isResultMatched: Mapped[bool | None] = mapped_column(Boolean)
    testId: Mapped[int | None] = mapped_column(Integer)
    testDetails: Mapped[dict | None] = mapped_column(JSON)
    biomarkerId: Mapped[int | None] = mapped_column(Integer)
    biomarkerDetails: Mapped[dict | None] = mapped_column(JSON)
    pdfJsonDetails: Mapped[dict | None] = mapped_column(JSON)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class ReviewResult(Base):
    __tablename__ = "ReviewResult"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    uploadResultSessionId: Mapped[int | None] = mapped_column(Integer)
    resultSampleIds: Mapped[dict | None] = mapped_column(JSON)
    reviewedBy: Mapped[int | None] = mapped_column(Integer)
    accessionIds: Mapped[dict | None] = mapped_column(JSON)
    reviewNote: Mapped[str | None] = mapped_column(String)
    isDiscarded: Mapped[bool | None] = mapped_column(Boolean)
    discardedReason: Mapped[str | None] = mapped_column(String)
    discardedBy: Mapped[int | None] = mapped_column(Integer)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class SampleProcessingPlate(Base):
    __tablename__ = "SampleProcessingPlate"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    sessionId: Mapped[int | None] = mapped_column(Integer)
    column: Mapped[str | None] = mapped_column(String)
    row: Mapped[str | None] = mapped_column(String)
    value: Mapped[str | None] = mapped_column(String)
    testOrPanelId: Mapped[int | None] = mapped_column(Integer)
    testOrPanelType: Mapped[str | None] = mapped_column(String)
    testOrPanelCode: Mapped[str | None] = mapped_column(String)
    testOrPanelName: Mapped[str | None] = mapped_column(String)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class SampleProcessingSession(Base):
    __tablename__ = "SampleProcessingSession"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    department: Mapped[str | None] = mapped_column(String)
    processingType: Mapped[str | None] = mapped_column(String)
    worklistIds: Mapped[dict | None] = mapped_column(JSON)
    subListIds: Mapped[dict | None] = mapped_column(JSON)
    plateId: Mapped[str | None] = mapped_column(String)
    comments: Mapped[str | None] = mapped_column(String)
    plateType: Mapped[str | None] = mapped_column(String)
    rows: Mapped[int | None] = mapped_column(Integer)
    columns: Mapped[int | None] = mapped_column(Integer)
    createdBy: Mapped[int | None] = mapped_column(Integer)
    status: Mapped[str | None] = mapped_column(String)
    isDiscarded: Mapped[bool | None] = mapped_column(Boolean)
    lastDiscardedBy: Mapped[int | None] = mapped_column(Integer)
    isExisting: Mapped[bool | None] = mapped_column(Boolean)
    existingIds: Mapped[dict | None] = mapped_column(JSON)
    isUploadFile: Mapped[bool | None] = mapped_column(Boolean)
    uploadFileDetails: Mapped[dict | None] = mapped_column(JSON)
    sampleIds: Mapped[dict | None] = mapped_column(JSON)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class SendOutOrderResult(Base):
    __tablename__ = "SendOutOrderResult"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    accessionId: Mapped[str | None] = mapped_column(String)
    orderId: Mapped[int | None] = mapped_column(Integer)
    biomarkerId: Mapped[int | None] = mapped_column(Integer)
    testId: Mapped[int | None] = mapped_column(Integer)
    result: Mapped[str | None] = mapped_column(String)
    version: Mapped[int | None] = mapped_column(Integer)
    biomarkerResultedAt: Mapped[str | None] = mapped_column(String)
    flag: Mapped[str | None] = mapped_column(String)
    addedBy: Mapped[int | None] = mapped_column(Integer)
    resultRemarks: Mapped[str | None] = mapped_column(String)
    isResultAvailable: Mapped[bool | None] = mapped_column(Boolean)
    microbialLoad: Mapped[str | None] = mapped_column(String)
    archivedAt: Mapped[dict | None] = mapped_column(JSON)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class SendOutOrderResultsArchive(Base):
    __tablename__ = "SendOutOrderResultsArchive"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    accessionId: Mapped[str | None] = mapped_column(String)
    orderId: Mapped[int | None] = mapped_column(Integer)
    biomarkerId: Mapped[int | None] = mapped_column(Integer)
    testId: Mapped[int | None] = mapped_column(Integer)
    result: Mapped[str | None] = mapped_column(String)
    version: Mapped[int | None] = mapped_column(Integer)
    biomarkerResultedAt: Mapped[str | None] = mapped_column(String)
    flag: Mapped[str | None] = mapped_column(String)
    addedBy: Mapped[int | None] = mapped_column(Integer)
    resultRemarks: Mapped[str | None] = mapped_column(String)
    isResultAvailable: Mapped[bool | None] = mapped_column(Boolean)
    microbialLoad: Mapped[str | None] = mapped_column(String)
    archivedAt: Mapped[dict | None] = mapped_column(JSON)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class SystemLabDocument(Base):
    __tablename__ = "SystemLabDocument"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    title: Mapped[str | None] = mapped_column(String)
    url: Mapped[str | None] = mapped_column(String)
    createdBy: Mapped[int | None] = mapped_column(Integer)
    isActive: Mapped[bool | None] = mapped_column(Boolean)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class TestAttachments(Base):
    __tablename__ = "TestAttachments"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    testId: Mapped[int | None] = mapped_column(Integer)
    fileName: Mapped[str | None] = mapped_column(String)
    mimeType: Mapped[str | None] = mapped_column(String)
    fileSize: Mapped[int | None] = mapped_column(Integer)
    path: Mapped[str | None] = mapped_column(String)
    secureUrl: Mapped[str | None] = mapped_column(String)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class TestPanel(Base):
    __tablename__ = "TestPanel"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class TestQuestion(Base):
    __tablename__ = "TestQuestion"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    question: Mapped[str | None] = mapped_column(String)
    options: Mapped[list | None] = mapped_column(ARRAY(String))
    answer: Mapped[str | None] = mapped_column(String)
    videoUrl: Mapped[str | None] = mapped_column(String)
    answerDescription: Mapped[str | None] = mapped_column(String)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class TestReportLayout(Base):
    __tablename__ = "TestReportLayout"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    title: Mapped[str | None] = mapped_column(String)
    code: Mapped[str | None] = mapped_column(String)
    url: Mapped[str | None] = mapped_column(String)
    isMultipleTable: Mapped[bool | None] = mapped_column(Boolean)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

class VersioningFile(Base):
    __tablename__ = "VersioningFile"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    module: Mapped[str | None] = mapped_column(String)
    entityId: Mapped[int | None] = mapped_column(Integer)
    createdBy: Mapped[int | None] = mapped_column(Integer)
    labId: Mapped[int | None] = mapped_column(Integer)
    secureUrl: Mapped[str | None] = mapped_column(String)
    mimeType: Mapped[str | None] = mapped_column(String)
    title: Mapped[str | None] = mapped_column(String)
    createdAt: Mapped[datetime | None] = mapped_column(DateTime)
    updatedAt: Mapped[datetime | None] = mapped_column(DateTime)

