"""Default ACL module catalog.

Seed data migrated verbatim from GkUserService AclModuleController
(addAclModuleMappingRawData). Loaded by POST /access-control/modules {seed:true}.
Kept here so the router stays readable.
"""

DEFAULT_ACL_MODULES: list[dict] = [
    {
        "module": "Lab",
        "feature": "Lab List View",
        "code": "labList",
        "description": "Access to view all labs in a list with their corresponding details (includes Filters and Column Settings).",
        "apis": [],
    },
    {
        "module": "Lab",
        "feature": "Lab List Edit",
        "code": "labEdit",
        "description": "Access to edit the corresponding details of all labs.",
        "apis": [],
    },
    {
        "module": "Lab",
        "feature": "Add New Lab",
        "code": "labAdd",
        "description": "Access to the functionality for adding a new lab in the system.",
        "apis": [],
    },
    {
        "module": "Lab",
        "feature": "Active/Inactive Lab",
        "code": "labToggle",
        "description": "Access to the functionality for activating or inactivating a lab in the system.",
        "apis": [],
    },
    {
        "module": "Facility",
        "feature": "Facility List View",
        "code": "facilityList",
        "description": "Access to view all facilities in a list with their corresponding details (includes Filters and Column Settings).",
        "apis": [],
    },
    {
        "module": "Facility",
        "feature": "Facility List Edit",
        "code": "facilityEdit",
        "description": "Access to edit the corresponding details of all facilities.",
        "apis": [],
    },
    {
        "module": "Facility",
        "feature": "Add New Facility",
        "code": "facilityAdd",
        "description": "Access to the functionality for adding a new facility in the system.",
        "apis": [],
    },
    {
        "module": "Facility",
        "feature": "Active/Inactive Facility",
        "code": "facilityToggle",
        "description": "Access to the functionality for activating or inactivating a facility in the system.",
        "apis": [],
    },
    {
        "module": "Facility",
        "feature": "CSV Download",
        "code": "facilityCsvDownload",
        "description": "Access to download the list of facilities with their corresponding details as a csv file.",
        "apis": [],
    },
    {
        "module": "Location",
        "feature": "Location List View",
        "code": "locationList",
        "description": "Access to view all locations in a list with their corresponding details (includes Filters and Column Settings).",
        "apis": [],
    },
    {
        "module": "Location",
        "feature": "Location List Edit",
        "code": "locationEdit",
        "description": "Access to edit the corresponding details of all locations.",
        "apis": [],
    },
    {
        "module": "Location",
        "feature": "Add New Location",
        "code": "locationAdd",
        "description": "Access to the functionality for adding a new location in the system.",
        "apis": [],
    },
    {
        "module": "Location",
        "feature": "Active/Inactive Location",
        "code": "locationToggle",
        "description": "Access to the functionality for activating or inactivating a location in the system.",
        "apis": [],
    },
    {
        "module": "Location",
        "feature": "CSV Download",
        "code": "locationCsvDownload",
        "description": "Access to download the list of locations with their corresponding details as a csv file.",
        "apis": [],
    },
    {
        "module": "Patient",
        "feature": "Patient List View",
        "code": "patientList",
        "description": "Access to view all patients in a list with their corresponding details (includes Filters and Column Settings).",
        "apis": [],
    },
    {
        "module": "Patient",
        "feature": "Patient",
        "code": "patientEdit",
        "description": "Access to edit the corresponding details of all patients.",
        "apis": [],
    },
    {
        "module": "Patient",
        "feature": "Add Patient",
        "code": "patientAdd",
        "description": "Access to the functionality for adding a new patient in the system.",
        "apis": [],
    },
    {
        "module": "Patient",
        "feature": "Active/InactivePatient",
        "code": "patientToggle",
        "description": "Access to the functionality for activating or inactivating a patient in the system.",
        "apis": [],
    },
    {
        "module": "Patient",
        "feature": "CSV Download",
        "code": "patientCsvDownload",
        "description": "Access to download the list of patients with their corresponding details as a csv file.",
        "apis": [],
    },
    {
        "module": "Patient",
        "feature": "Activity Log",
        "code": "patientActivityLog",
        "description": "Access to view the activity log of a specific patient.",
        "apis": [],
    },
    {
        "module": "TestOrder",
        "feature": "Test Orders List View",
        "code": "testOrderList",
        "description": "Access to view all test orders in a list with their corresponding details.",
        "apis": [],
    },
    {
        "module": "TestOrder",
        "feature": "Test Orders List Edit",
        "code": "testOrderEdit",
        "description": "Access to edit the corresponding details of all test orders.",
        "apis": [],
    },
    {
        "module": "TestOrder",
        "feature": "Add New Test Order",
        "code": "testOrderAdd",
        "description": "Access to the functionality for adding a new test order in the system.",
        "apis": [],
    },
    {
        "module": "TestOrder",
        "feature": "CSV Download",
        "code": "testOrderCsvDownload",
        "description": "Access to download the list of test orders with their corresponding details as a csv file.",
        "apis": [],
    },
    {
        "module": "TestOrder",
        "feature": "Bulk Test Order List View",
        "code": "testOrderBulkList",
        "description": "Access to view all bulk test orders in a list with their corresponding details.",
        "apis": [],
    },
    {
        "module": "TestOrder",
        "feature": "Import Bulk Test Order",
        "code": "testOrderImportBulk",
        "description": "Access to the functionality for importing a new bulk test order file in the system.",
        "apis": [],
    },
    {
        "module": "TestOrder",
        "feature": "Cancel Test Order",
        "code": "testOrderCancel",
        "description": "Access to the functionality for canceling a test order in the system.",
        "apis": [],
    },
    {
        "module": "TestOrder",
        "feature": "Result Correction",
        "code": "testOrderResultCorrection",
        "description": "Access to the functionality for re-uploading a new test report over the previous one.",
        "apis": [],
    },
    {
        "module": "TestOrder",
        "feature": "Sample Activity Log",
        "code": "sampleActivityLog",
        "description": "Access to view the activity log of a specific sample.",
        "apis": [],
    },
    {
        "module": "TestOrderSample",
        "feature": "Sample List View",
        "code": "sampleList",
        "description": "Access to view all samples in a list with their corresponding details.",
        "apis": [],
    },
    {
        "module": "TestOrderSample",
        "feature": "CSV Download",
        "code": "sampleCsvDownload",
        "description": "Access to download the list of samples with their corresponding details as a csv file.",
        "apis": [],
    },
    {
        "module": "TestOrderSample",
        "feature": "Mark as Sendout",
        "code": "sampleSendOut",
        "description": "Access to the functionality for designating samples as sent to a third-party lab.",
        "apis": [],
    },
    {
        "module": "TestOrderSample",
        "feature": "Result Upload",
        "code": "sampleResultUpload",
        "description": "Access to the functionality for uploading the result to a specific sample.",
        "apis": [],
    },
    {
        "module": "Accession",
        "feature": "Accession a sample",
        "code": "sample",
        "description": "Access to the functionality for accessioning a specific sample.",
        "apis": [],
    },
    {
        "module": "TestPanel",
        "feature": "Test Panel List View",
        "code": "panelList",
        "description": "Access to view all test panels in a list with their corresponding details.",
        "apis": [],
    },
    {
        "module": "TestPanel",
        "feature": "Test Panel List Edit",
        "code": "panelEdit",
        "description": "Access to edit the corresponding details of all test panels.",
        "apis": [],
    },
    {
        "module": "TestPanel",
        "feature": "Add New Test Panel",
        "code": "panelAdd",
        "description": "Access to the functionality for adding a new test panel in the system.",
        "apis": [],
    },
    {
        "module": "TestPanel",
        "feature": "Active/Inactive Test Panel",
        "code": "panelToggle",
        "description": "Access to the functionality for activating or inactivating a test panel in the system.",
        "apis": [],
    },
    {
        "module": "TestPanel",
        "feature": "CSV Download",
        "code": "panelCsvDownload",
        "description": "Access to download the list of test panels with their corresponding details as a csv file.",
        "apis": [],
    },
    {
        "module": "Result",
        "feature": "Result List View",
        "code": "resultList",
        "description": "Access to view all samples in a list with their corresponding details.",
        "apis": [],
    },
    {
        "module": "Result",
        "feature": "Upload XLS File",
        "code": "panelUploadXLS",
        "description": "Access to the functionality for generating bulk results of specific samples in the system.",
        "apis": [],
    },
    {
        "module": "SendOuts",
        "feature": "Sendouts List View",
        "code": "sendoutsList",
        "description": "Access to view all sendouts in a list with their corresponding details.",
        "apis": [],
    },
    {
        "module": "SendOuts",
        "feature": "CSV Download",
        "code": "sendOutsCSV",
        "description": "Access to download the list of sendouts history with their corresponding details as a csv file.",
        "apis": [],
    },
    {
        "module": "SendOuts",
        "feature": "Samples CSV Download",
        "code": "sendoutSampleCsv",
        "description": "Access to download the list of sendout samples with their corresponding details as a csv file.",
        "apis": [],
    },
    {
        "module": "QrCodes",
        "feature": "QR Codes List View",
        "code": "QRCodesList",
        "description": "Access to view all QR codes in a list with their corresponding details.",
        "apis": [],
    },
    {
        "module": "QrCodes",
        "feature": "Generate QR Code",
        "code": "QRCodesGenerate",
        "description": "Access to the functionality for generating QR code of a specific test panel in the system.",
        "apis": [],
    },
    {
        "module": "StateReporting",
        "feature": "State Reporting List View",
        "code": "stateReportingList",
        "description": "Access to view all state reportings in a list with their corresponding details.",
        "apis": [],
    },
    {
        "module": "Barcode",
        "feature": "Barcodes List View",
        "code": "barcodesList",
        "description": "Access to view all barcodes in a list.",
        "apis": [],
    },
    {
        "module": "Barcode",
        "feature": "Regenerate Barcodes",
        "code": "barcodeRegenerate",
        "description": "Access to the functionality for re-generating barcodes of a specific test panel in the system.",
        "apis": [],
    },
    {
        "module": "SystemSettings",
        "feature": "Dropdowns",
        "code": "dropdowns",
        "description": "Access to the functionality for managing the data displayed in system dropdowns.",
        "apis": [],
    },
    {
        "module": "AccessControl",
        "feature": "Access Control List View",
        "code": "accessControlList",
        "description": "Access to view all roles in a list with their corresponding permissions.",
        "apis": [],
    },
    {
        "module": "AccessControl",
        "feature": "Access Control List Edit",
        "code": "accessControlEdit",
        "description": "Access to edit the corresponding permissions of all roles.",
        "apis": [],
    },
    {
        "module": "AccessControl",
        "feature": "Add Role Access",
        "code": "accessControlAdd",
        "description": "Access to the functionality for adding a new access role in the system.",
        "apis": [],
    },
]
